### ISSUE TITLE
Security: Support for useMethods setting on widget

### ISSUE THREAD

**Issue by workflow** [JackAdams/meteor-editable-text#23]
Hi,

it would be awesome to be able to set `useMethods` to `true` or `false` on a per widget basis.

What are you thoughts on this?

My rationale is that I don't really like the duplication of security logic that comes with having to maintain allow/deny rules AND server-side rules simultaneously.
For this reason, I'm running with allow/deny rules (specifically [ongoworks:security](https://atmospherejs.com/ongoworks/security)) only and have `useMethods = false` per default.

However, in some cases where I need more control, it would be great to set useMethods to true for just one widget, or maybe even pass a meteor method name like [autoform](https://atmospherejs.com/aldeed/autoform) does?

**Comment by JackAdams** [comment]
If you initialize the widget with `useMethod = false` (note: no 's' at the end), then it will make a client side update that will get validated by your allow/deny rules.  The default setting is `EditableText.useMethods = true;` which you can set to `EditableText.useMethods = false;` in a client side js file if you want to change the default behaviour for all widget instances to making client side updates.

This functionality is in there because I find I use it myself a lot.

**Comment by workflow** [comment]
Awesome, thank you!

The missing 's' is logical but I I could not guess. :) Shall we add it to the readme?

**Comment by JackAdams** [comment]
Yeah, there's a couple of undocumented things that should be in the readme.
