### ISSUE TITLE
Could not execute callback. Reason: no callback function .... registered via EditableText.registerCallbacks.

### ISSUE THREAD

**Issue by etaiklein** [JackAdams/meteor-editable-text#33]
Trying my best to replicate here:

Basically, I think I'm misunderstanding something basic about how to register callbacks. 
As far as I understand I just need to write a callback function in my javascript like

```
EditableText.registerCallbacks({
  test : function() {
    console.log("test");
  }
});
```

and call it in my html like

```
{{> editableText collection="posts" field="message" placeholder="Post message" removeEmpty=true afterUpdate="test" wysiwyg=true substitute='<i class="fa fa-pencil"></i>'}}
```

On meteorpad it silently fails, but in my app I get the following error :

```
errorClass {error: "Could not execute callback. Reason: no callback fu…en registered via EditableText.registerCallbacks.", reason: undefined, details: undefined, message: "[Could not execute callback. Reason: no callback f…n registered via EditableText.registerCallbacks.]", errorType: "Meteor.Error"…}
details: undefined
error: "Could not execute callback. Reason: no callback function called "test" has been registered via      EditableText.registerCallbacks."
errorType: "Meteor.Error"
message: "[Could not execute callback. Reason: no callback function called "test" has been registered via EditableText.registerCallbacks.]"
reason: undefined
```

http://meteorpad.com/pad/aaZjjWaqYqz6eramZ/Copy%20of%20Editable%20Test%202%20(1)

**Comment by JackAdams** [comment]
Thanks for reporting this.  All your syntax looks right.  I'll download the meteorpad repro and see if I can figure out what's going on.

**Comment by JackAdams** [comment]
The callbacks were registered in the `client.js` file not the `common.js` file.  Because the mutator methods from the `EditableText` widget are latency comped, the callbacks are fired on both client and server.  That error was getting passed back from the server (which the meteorpad console seems to swallow -- wasn't expecting that ...).  Anyway, moving the `EditableText.registerCallbacks({ ... })` to the `common.js` fixes the problem, as the callback is now registered on both client and server.
See working version here: http://meteorpad.com/pad/S5nAE52b7k5qZzC7Y/Copy%20of%20Editable%20Test%202%20%282%29

**Comment by etaiklein** [comment]
Awesome! Thanks.
