### ISSUE TITLE
edit array of embedded documents

### ISSUE THREAD

**Issue by manineel** [JackAdams/meteor-editable-text#40]
I have a collection as follows in my Meteor app

{ "_id" : ObjectId("55943a2488bde2cc2ea084c7"), "adminId" : "ZuSzdGWxixaePMWyB",
 "details" : [ { "header" : "h1", "body" : "b1" }, { "header" : "h2", "body" : "
b2" } ], "test" : "tes" }

I need to show all the headers and bodies of details section in one page. My HTML looks as follows.

<h2 class="editable-text-trigger">
{{> editableText collection="CollegeProfiles" field="header" removeEmpty=true placeholder="title" substitute='<i class="fa fa-pencil"></i>'}
</h2>

My js looks as follows... 
  Template.admin_profile.helpers ({
        profileDetails : function() {
        var doc_profile = CollegeProfilesCollection.findOne({adminId:Meteor.userId()});
          if(doc_profile)
          {
            return doc_profile.details;
          }

```
}
```

  });

I am able to view the headers, but when I edit , it does not updates. Could you help.

**Comment by JackAdams** [comment]
This package isn't really designed to do what you're trying to do (edit subdocuments in arrays), but here's a [working example on Meteorpad](http://meteorpad.com/pad/LaYRYotd7oxuEyoYa/Editable%20text%20for%20array%20of%20objects) using a few workarounds.

**Note:** because the version of `babrahams:editable-text` on Meteorpad isn't up to date for some reason, I've added the `babrahams:editable-text-wysiwyg-bootstrap-3` package instead, which has a dependency on `babrahams:editable-text`, and this causes it to pull in the latest version.  In an app you're developing on your local machine, you can just `meteor add babrahams:editable-text` and the latest version should get added.

**Comment by manineel** [comment]
Thanks a lot!!.. I will check how I can do this in my code...
