### ISSUE TITLE
What happened to this.oldValue?

### ISSUE THREAD

**Issue by mvanio** [JackAdams/meteor-editable-text#49]
I need to do some data validation on a few fields on set up a callback to check before & after values. Trouble is, `this.oldValue` seems to have been removed. Maybe it's only available on certain callback hooks, or maybe it's been superceded - please let us know.

Or - is there a recommended method of data validation and I'm trying to reinvent the wheel here?

Awesome work BTW.

**Comment by JackAdams** [comment]
The only callbacks `this.oldValue` is available on are `beforeUpdate` and `afterUpdate`.  There was a regression in a recent version that may have accidentally caused its disappearance, but this should be fixed in `0.8.3`.

Besides the most basic data validation (e.g. `acceptEmpty=true` or `type="number"`), this package doesn't do any checks.  Using callbacks, as you've described, is the best way.

If `meteor update` doesn't solve the problem, let me know and I'll take another look at it.

**Comment by mvanio** [comment]
I've tried with both `beforeUpdate` and `afterUpdate` with 0.8.3 but `this.oldValue` is still `undefined`.
Any ideas?

```
EditableText.registerCallbacks({
  beNumeric: function(){
    console.log(this.oldValue);
    console.log(this.newValue);
  }
});
```

```
undefined
22
```

**Comment by JackAdams** [comment]
Sorry about that.  It should be working again.  Thanks for bringing this up.
